sudo: required
  services:
    - docker

language: generic     


before_install:
  - docker build -t clausenc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clausenc/docker-react npm run test  


    
