sudo: required
  services:
    - docker

language: generic     


before_install:
  - docker build -t clausenc/docker-react -f Dockerfile.dev .

script:
  - docker run clausenc/docker-react npm run test -- --coverage
  